
MCU = RP2040
BOOTLOADER = rp2040
WS2812_DRIVER = vendor
MOUSEKEY_ENABLE = yes
LTO_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
WEAR_LEVELING_DRIVER = rp2040_flash


